### ISSUE TITLE
Account properties in /accounts

### ISSUE THREAD

**Issue by sightorld** [tonindexer/anton#27]
Same as the issue #26, without making additional requests with specific parameters or to different methods, single account in /accounts response lacks any information on the:
- Amount of transactions
- Amount of owned NFTs
- Amount of minted NFTs
- Amount of jetton wallets
- Amount of jetton holders and nft holders for `contract = jetton_minter` and `contract = nft_collection` respectively, along with the amount of NFTs in the collection and total jetton pool on the account

**Comment by iam047801** [comment]
Extended `/accounts/aggregated` with needed functionality. This feature will be released in v0.3.3.

**Comment by valeria6462** [comment]
No se cómo usar mi cuenta, desde que la creé eh tratado de acceder a todo lo que he hecho de la minería de ton y not , y ya dejen de sacarle provecho a lo q no se manejar y mejor ayedenme a alcanzar una décima parte mínimo
