### ISSUE TITLE
How to get method name from method hash?

### ISSUE THREAD

**Issue by fishTsai20** [tonindexer/anton#40]
the response of /accounts has a field get_method_hashes.
I want to know how to parse these hashes to method_name?

**Comment by iam047801** [comment]
That is impossible, as get method hash is a crc32 hash from method name. You can only try to brute force possible method names.

**Comment by fishTsai20** [comment]
But I see curl -X GET 'https://anton.tools/api/v0/contract/interfaces' returns method_name
