### ISSUE TITLE
How to run anton without docker?

### ISSUE THREAD

**Issue by fishTsai20** [tonindexer/anton#41]
MacBook-Pro:anton isachoi$ ./anton indexer --contract-dir /root/anton/abi/known

dyld[68894]: Library not loaded: @rpath/libemulator.dylib
  Referenced from: <6A2CB809-B12E-35DF-88B7-0F6D281DE22B> /Users/isachoi/GolandProjects/anton/anton
  Reason: tried: '../lib/darwin/libemulator.dylib' (no such file), '../lib/darwin/libemulator.dylib' (no such file)
Abort trap: 6

**Comment by iam047801** [comment]
You need to build emulator library by yourself (refer to the Dockerfile) or download it from the [TON Blockchain releases](https://github.com/ton-blockchain/ton/releases).
